### ISSUE TITLE
Can't compile C++ files (api.hpp missing)

### ISSUE THREAD

**Issue by theMathR** [Vault-Software-Team/Vault-Engine-Old#13]
I made a new C++ script, and when I try to compile it, i get this error in the console:
```
In file included from assets/scripts/Ground.cpp:1:
assets/scripts/Ground.hpp:2:10: fatal error: api.hpp: No such file or directory
    2 | #include <api.hpp>
      |          ^~~~~~~~~
compilation terminated.
```

**Comment by koki10190** [comment]
I think i just forgot to compile the CppScripting.cpp file.. cause it works after i compiled it
This is definitely strange

**Comment by koki10190** [comment]
Probably fixed this issue, needs testing

**Comment by koki10190** [comment]
Probably fixed this issue, closing until further notice
